version: "3.8"

name: "dynamodb"

services:
  db:
    image: "amazon/dynamodb-local:latest"
    command: "-jar DynamoDBLocal.jar -inMemory -sharedDb"
    labels:
      - dynamoDb-local
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", 'if [ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]; then exit 0; else exit 1; fi']
      interval: 5s
      timeout: 5s
      retries: 10
